---@class MemoirGlobal
---@field biter_names name_info[]
---@field biter_name_count integer
---@field biter_memoir_count integer

---@class name_info
---@field name string
---@field pronouns support_pronouns|"either"
---@field special_memoir? LocalisedString
---@field color? Color

---@alias support_pronouns "male"|"female"|"their"

---@return name_info[]
function default_names()
    ---@type name_info[]
    return {
        {pronouns = "male",   name = "George"},
        {pronouns = "female", name = "Sue"},
        {pronouns = "female", name = "Mary"},
        {pronouns = "male",   name = "Bob"},
        {pronouns = "male",   name = "Cho"},
        {pronouns = "male",   name = "Lee"},
        {pronouns = "male",   name = "Henry"},
        {pronouns = "female", name = "Alice"},
        {pronouns = "female", name = "Amanda"},
        {pronouns = "either", name = "Tyler"},
        {pronouns = "male",   name = "Kyle"},
        {pronouns = "male",   name = "Sam"},
        {pronouns = "male",   name = "Greg"},
        {pronouns = "male",   name = "Varik", special_memoir = {"biter-memoirs-special.Varik"}},
        {pronouns = "female", name = "Liz"},
        {pronouns = "female", name = "Lauren"},
        {pronouns = "female", name = "Eve"},
        {pronouns = "female", name = "Cathy"},
        {pronouns = "male",   name = "Hao"},
        {pronouns = "either", name = "Indy"},
        {pronouns = "male",   name = "Buster"},
        {pronouns = "male",   name = "Buddy"},
        {pronouns = "either", name = "Chomps"},
        {pronouns = "female", name = "EmilyFlambe", special_memoir = {"biter-memoirs-special.EmilyFlambe"}},
        {pronouns = "male",   name = "Nilaus", special_memoir = {"biter-memoirs-special.Nilaus"}},
        {pronouns = "male",   name = "Nefrums", special_memoir = {"biter-memoirs-special.Nefrums"}},
        {pronouns = "male",   name = "AntiElitz"},
        {pronouns = "male",   name = "NotExfret"},
        {pronouns = "either", name = "Killer"},
        {pronouns = "either", name = "NomNoms"},
        {pronouns = "either", name = "Hungerz"},
        {pronouns = "either", name = "Taylor"},
        {pronouns = "male",   name = "Bill"},
        {pronouns = "male",   name = "Chad"},
        {pronouns = "male",   name = "Carson"},
        {pronouns = "female", name = "Olivia"},
        {pronouns = "male",   name = "_CodeGreen"},
        {pronouns = "male",   name = "Periklis"},
        {pronouns = "female", name = "Jazlene"},
        {pronouns = "male",   name = "Noah"},
        {pronouns = "male",   name = "Liam"},
        {pronouns = "female", name = "Emerald"},
        {pronouns = "female", name = "Ruby"},
        {pronouns = "either", name = "Ymir"},
        {pronouns = "either", name = "Meow"},
        {pronouns = "female", name = "Aria"},
        {pronouns = "female", name = "Katrina"},
        {pronouns = "female", name = "Scott"},
        {pronouns = "male",   name = "Mr. Bitter"},
        {pronouns = "male",   name = "Johny"},
        {pronouns = "male",   name = "Tommy"},
        {pronouns = "female", name = "Mrs. Bitter"},
        {pronouns = "male",   name = "Bitter Jr."},
        {pronouns = "either", name = "Bitey"},
        {pronouns = "either", name = "Ipsum Lorem"},
        {pronouns = "male",   name = "Bob Ross"},
        {pronouns = "either", name = "Kid"},
        {pronouns = "their",  name = "Alien"},
        {pronouns = "their",  name = "Unit"},
        {pronouns = "female", name = "Amelia"},
        {pronouns = "male",   name = "John Smith"},
        {pronouns = "female", name = "Charlotte"},
        {pronouns = "female", name = "Amy"},
        {pronouns = "female", name = "Rose"},
        {pronouns = "female", name = "Daisy"},
        {pronouns = "female", name = "Bubbles"},
        {pronouns = "female", name = "Ava"},
        {pronouns = "their",  name = "Asher", special_memoir = {"biter-memoirs-special.Asher"}},
        {pronouns = "male",   name = "Isaiah"},
        {pronouns = "male",   name = "Juan"},
        {pronouns = "female", name = "Maria"},
        {pronouns = "male",   name = "Julio"},
        {pronouns = "female", name = "Ivy"},
        {pronouns = "female", name = "Ella"},
        {pronouns = "male",   name = "Eli"},
        {pronouns = "male",   name = "Nathan"},
        {pronouns = "their",  name = "Random"},
        {pronouns = "their",  name = "nullptr"},
        {pronouns = "their",  name = "Megan"},
        {pronouns = "male",   name = "Cueball"},
        {pronouns = "male",   name = "Rex"},
        {pronouns = "either", name = "Ale"},
        {pronouns = "male",   name = "Good Boi", special_memoir = {"biter-memoirs-special.Good Boi"}},
        {pronouns = "male",   name = "Soto"},
        {pronouns = "either", name = "I Hungerz"},
        {pronouns = "their",  name = "Bug"},
        {pronouns = "female", name = "Zoe"},
        {pronouns = "male",   name = "Kehlani"},
        {pronouns = "female", name = "Iris"},
        {pronouns = "male",   name = "Chase"},
        {pronouns = "male",   name = "Jacob"},
        {pronouns = "female", name = "Caroline"},
        {pronouns = "male",   name = "Beau"},
        {pronouns = "female", name = "Claire"},
        {pronouns = "female", name = "Vivian"},
        {pronouns = "male",   name = "Mr. Spitz"},
        {pronouns = "male",   name = "Drop Tables"},
        {pronouns = "male",   name = "Bud"},
        {pronouns = "their",  name = "Coronavirus"},
        {pronouns = "female", name = "Derpy"},
        {pronouns = "male",   name = "DinnerBone"},
        {pronouns = "either", name = "SoonToBeDead"},
        {pronouns = "female", name = "Lizzy"},
        {pronouns = "male",   name = "Wavetrex"},
        {pronouns = "male",   name = "Brevven"},
        {pronouns = "either", name = "Citizen 1"},
        {pronouns = "either", name = "Citizen 2"},
        {pronouns = "either", name = "Citizen 4"},
        {pronouns = "either", name = "GGs", special_memoir = {"biter-memoirs-special.GGs"}},
        {pronouns = "male",   name = "Klonan"},
        {pronouns = "male",   name = "Kovarex"},
        {pronouns = "their",  name = "Factorio", special_memoir = {"biter-memoirs-special.Factorio"}},
        {pronouns = "either", name = "Scorpion"},
        {pronouns = "male",   name = "DoshDoshington", special_memoir = {"biter-memoirs-special.DoshDoshington"}},
        {pronouns = "male",   name = "Comkat"},
        {pronouns = "their",  name = "1000x tech cost"},
        {pronouns = "male",   name = "Earendel", special_memoir = {"biter-memoirs-special.Earendel"}},
        {pronouns = "either", name = "Pupper"},
        {pronouns = "either", name = "Doggo"},
        {pronouns = "either", name = "Bork"},
        {pronouns = "male",   name = "Garath"},
        {pronouns = "male",   name = "Max"},
        {pronouns = "female", name = "Minnie"},
        {pronouns = "male",   name = "Mac"},
        {pronouns = "female", name = "Wilt"},
        {pronouns = "male",   name = "King"},
        {pronouns = "male",   name = "Prince"},
        {pronouns = "male",   name = "Loki"},
        {pronouns = "female", name = "Chen"},
        {pronouns = "female", name = "Michelle"},
        {pronouns = "female", name = "Jenny"},
        {pronouns = "male",   name = "Forest"},
        {pronouns = "male",   name = "Bilka"},
        {pronouns = "male",   name = "Fred Rogers"},
        {pronouns = "male",   name = "Dasher"},
        {pronouns = "male",   name = "Rudolph"},
        {pronouns = "male",   name = "Raiguard"},
        {pronouns = "male",   name = "Bobingabout"},
        {pronouns = "male",   name = "TravisSucks"},
        {pronouns = "female", name = "Demi Lovato"},
        {pronouns = "their",  name = "[item=iron-plate]"},
        {pronouns = "either", name = "quirky"},
        {pronouns = "their",  name = "[item=pistol]"},
        {pronouns = "their",  name = "[item=artillery-wagon-cannon]"},
        {pronouns = "their",  name = "[item=submachine-gun]"},
        {pronouns = "male",   name = "Sparticus"},
        {pronouns = "male",   name = "Monty Python"},
        {pronouns = "female", name = "Majesty"},
        {pronouns = "female", name = "Mae"},
        {pronouns = "male",   name = "Smith"},
        {pronouns = "male",   name = "Tao"},
        {pronouns = "male",   name = "Buddha"},
        {pronouns = "male",   name = "Jesus"},
        {pronouns = "male",   name = "Obama"},
        {pronouns = "male",   name = "boskid"},
        {pronouns = "male",   name = "Erythion"},
        {pronouns = "male",   name = "Rseding"},
        {pronouns = "male",   name = "Loren"},
        {pronouns = "male",   name = "mikelat"},
        {pronouns = "female", name = "damzl"},
        {pronouns = "male",   name = "alcari"},
        {pronouns = "male",   name = "friendcalledfive", special_memoir = {"biter-memoirs-special.friendcalledfive"}},
        {pronouns = "male",   name = "Moridrex"},
        {pronouns = "their",  name = "GT:NH"},
        {pronouns = "either", name = "\"Quotes\""},
        {pronouns = "either", name = "Biter no. 457098q709827092457"},
        {pronouns = "either", name = ":)"},
        {pronouns = "their",  name = "Fourier Transform"},
        {pronouns = "male",   name = "Galous"},
        {pronouns = "male",   name = "Everiste"},
        {pronouns = "male",   name = "Abel"},
        {pronouns = "male",   name = "Tony"},
        {pronouns = "male",   name = "SquidCoder"},
        {pronouns = "male",   name = "Michal"},
        {pronouns = "male",   name = "Tomas"},
        {pronouns = "male",   name = "Albert"},
        {pronouns = "male",   name = "Twinsen"},
        {pronouns = "male",   name = "Robert"},
        {pronouns = "male",   name = "Nick"},
        {pronouns = "female", name = "Wube"},
        {pronouns = "either", name = "Person"},
        {pronouns = "male",   name = "Batman"},
        {pronouns = "male",   name = "Ken"},
        {pronouns = "male",   name = "Scoob", special_memoir = {"biter-memoirs-special.Scoob"}},
        {pronouns = "either", name = "Nemesis"},
        {pronouns = "their",  name = "SPM"},
        {pronouns = "either", name = "The factory must grow"},
        {pronouns = "their",  name = "r/factoriohno"},
        {pronouns = "female", name = "Abby"},
        {pronouns = "male",   name = "Mike"},
        {pronouns = "male",   name = "Pyanodon"},
        {pronouns = "female", name = "Demi"},
        {pronouns = "male",   name = "Dominus_Pullum"},
        {pronouns = "male",   name = "FatalOwl"},
        {pronouns = "female", name = "SkyeOfBreeze"},
        {pronouns = "male",   name = "Brad"},
        {pronouns = "male",   name = "Bradley"},
        {pronouns = "male",   name = "Ronald"},
        {pronouns = "male",   name = "Harry"},
        {pronouns = "female", name = "Hermione"},
        {pronouns = "male",   name = "PokTux"},
        {pronouns = "male",   name = "Pikachu", special_memoir = {"biter-memoirs-special.Pikachu"}},
        {pronouns = "male",   name = "Pikachu2", special_memoir = {"biter-memoirs-special.Pikachu2"}},
        {pronouns = "female", name = "Vaporeon"},
        {pronouns = "male",   name = "Steve"},
        {pronouns = "male",   name = "Elon Musk", special_memoir = {"biter-memoirs-special.Elon Musk"}},
        {pronouns = "male",   name = "Fermat", special_memoir = {"biter-memoirs-special.Fermat"}},
        {pronouns = "male",   name = "Nova"},
        {pronouns = "female", name = "Isabelle"},
        {pronouns = "male",   name = "Foxabilo"},
        {pronouns = "male",   name = "Carl Sagan", special_memoir = {"biter-memoirs-special.Carl Sagan"}},
        {pronouns = "male",   name = "Cobai", special_memoir = {"biter-memoirs-special.Cobai"}},
        {pronouns = "male",   name = "BlackATM", special_memoir = {"biter-memoirs-special.BlackATM"}},
        {pronouns = "male",   name = "Lebothegizebo", special_memoir = {"biter-memoirs-special.Lebothegizebo"}},
        {pronouns = "male",   name = "sassxolotl", special_memoir = {"biter-memoirs-special.sassxolotl"}},
        {pronouns = "male",   name = "Randall", special_memoir = {"biter-memoirs-special.Randall"}},
        {pronouns = "male",   name = "Sun Tzu", special_memoir = {"biter-memoirs-special.Sun Tzu"}},
        {pronouns = "female", name = "Debbie"},
        {pronouns = "female", name = "Shelby"},
        {pronouns = "male",   name = "Jeison"},
        {pronouns = "female", name = "Tragedeigh"},
        {pronouns = "female", name = "Kynnedee"},
        {pronouns = "female", name = "Emeilla"},
        {pronouns = "female", name = "Jmily"},
        {pronouns = "female", name = "Phaedra"},
        {pronouns = "female", name = "Deyzi"},
        {pronouns = "female", name = "Mom"},
        {pronouns = "either", name = "fren"},
        {pronouns = "male",   name = "Spongebob"},
        {pronouns = "male",   name = "Rasputin"},
        {pronouns = "their",  name = "Bitertron 3000"},
        {pronouns = "their",  name = "Archangel666"},
        {pronouns = "their",  name = "propertyrandomizer"},
        {pronouns = "male",   name = "Bluey"},
        {pronouns = "male",   name = "Blackbeard"},
        {pronouns = "female", name = "Sophia"},
        {pronouns = "male",   name = "Aiden"},
        {pronouns = "female", name = "Emma"},
        {pronouns = "male",   name = "Lucas"},
        {pronouns = "male",   name = "Mason"},
        {pronouns = "female", name = "Harper"},
        {pronouns = "male",   name = "Caleb"},
        {pronouns = "male",   name = "Samuel"},
        {pronouns = "female", name = "Grace"},
        {pronouns = "female", name = "Paige"},
        {pronouns = "female", name = "Scarlett"},
        {pronouns = "male",   name = "Riley"},
        {pronouns = "female", name = "Natalie"},
        {pronouns = "female", name = "Victoria"},
        {pronouns = "either", name = "Doubt"},
        {pronouns = "either", name = "Guilt"},
        {pronouns = "female", name = "Sarah"},
        {pronouns = "female", name = "Bonita"},
        {pronouns = "female", name = "Bonnie"},
        {pronouns = "male",   name = "engelbert"},
        {pronouns = "male",   name = "Casper"},
        {pronouns = "male",   name = "Caspian"},
        {pronouns = "either", name = "Coffee"},
        {pronouns = "male",   name = "Reggie"},
        {pronouns = "male",   name = "Walter"},
        {pronouns = "male",   name = "Joe"},
        {pronouns = "male",   name = "Bach"},
        {pronouns = "female", name = "Myrna"},
        {pronouns = "female", name = "Bertha"},
        {pronouns = "male",   name = "Boris"},
        {pronouns = "female", name = "Hillary"},
        {pronouns = "female", name = "Margaret"},
        {pronouns = "female", name = "Catherine"},
        {pronouns = "male",   name = "Peter"},
        {pronouns = "male",   name = "Yousaf"},
        {pronouns = "male",   name = "Leonard"},
        {pronouns = "male",   name = "Newton"},
        {pronouns = "male",   name = "Einstein"},
        {pronouns = "either", name = "Fear"},
        {pronouns = "male",   name = "Bessie"},
        {pronouns = "female", name = "Tabitha"},
        {pronouns = "male",   name = "Ron"},
        {pronouns = "male",   name = "Melvin"},
        {pronouns = "female", name = "Angelica"},
        {pronouns = "their",  name = "Egg"},
        {pronouns = "male",   name = "Javier"},
        {pronouns = "female", name = "Simona"},
        {pronouns = "their",  name = "The Knight"},
        {pronouns = "male",   name = "Thanos"},
        {pronouns = "male",   name = "Thor"},
        {pronouns = "male",   name = "Stark"},
        {pronouns = "male",   name = "The Little Prince"},
        {pronouns = "male",   name = "Senator Bites"},
        {pronouns = "male",   name = "Doctor Johnson"},
        {pronouns = "male",   name = "Ferb"},
        {pronouns = "their",  name = "e"},
        {pronouns = "female", name = "Big Bertha"},
        {pronouns = "female", name = "Katniss"},
        {pronouns = "female", name = "Geranium"},
        {pronouns = "female", name = "Jolina"},
        {pronouns = "male",   name = "Juanito"},
        {pronouns = "their",  name = "Eigenvector"},
        {pronouns = "male",   name = "Perry"},
        {pronouns = "their",  name = "chatGPT"},
        {pronouns = "male",   name = "Chris"},
        {pronouns = "male",   name = "Anush"},
        {pronouns = "female", name = "Nidhi"},
        {pronouns = "male",   name = "Dwayne"},
        {pronouns = "male",   name = "Emperor"},
        {pronouns = "female", name = "Empress"},
        {pronouns = "male",   name = "Khan"},
        {pronouns = "male",   name = "Billy"},
        {pronouns = "male",   name = "Little Billy"},
        {pronouns = "male",   name = "James"},
        {pronouns = "male",   name = "John"},
        {pronouns = "male",   name = "Jay"},
        {pronouns = "female", name = "Paisley"},
        {pronouns = "female", name = "Naomi"},
        {pronouns = "either", name = "Swifty"},
        {pronouns = "female", name = "Carolyn"},
        {pronouns = "male",   name = "Ash"},
        {pronouns = "male",   name = "Luca"},
        {pronouns = "either", name = "PennyJim", special_memoir = {"biter-memoirs-special.PennyJim"}},
        {pronouns = "male",   name = "Fireball", special_memoir = {"biter-memoirs-special.Fireball"}},
        {pronouns = "either", name = "[item=depleted-uranium-fuel-cell,quality=legendary]"},
        {pronouns = "male",   name = "Thomas"},
        {pronouns = "female", name = "Lua"},
        {pronouns = "female", name = "Loli"},
        {pronouns = "female", name = "Dianna"},
        {pronouns = "female", name = "Kara"},
        {pronouns = "female", name = "Aubrey"},
        {pronouns = "female", name = "Hope"},
        {pronouns = "female", name = "Latisha"},
        {pronouns = "female", name = "Rebecca"},
        {pronouns = "female", name = "Tori"},
        {pronouns = "male",   name = "Trace"},
        {pronouns = "their",  name = "The 2008 Financial Crisis"},
        {pronouns = "female", name = "Jennie"},
        {pronouns = "female", name = "Amber"},
        {pronouns = "female", name = "Lilu"},
        {pronouns = "female", name = "Kim"},
        {pronouns = "female", name = "Stacy"},
        {pronouns = "female", name = "Pepper"},
        {pronouns = "female", name = "Brittney"},
        {pronouns = "female", name = "Joan"},
        {pronouns = "female", name = "Kylie"},
        {pronouns = "female", name = "Mia"},
        {pronouns = "female", name = "Katherine"},
        {pronouns = "female", name = "Luna"},
        {pronouns = "female", name = "Nora"},
        {pronouns = "female", name = "akip"},
        {pronouns = "female", name = "Brooke"},
        {pronouns = "female", name = "Eliza"},
        {pronouns = "female", name = "Melanie"},
        {pronouns = "female", name = "Piper"},
        {pronouns = "male",   name = "Upside-down Eye"},
        {pronouns = "female", name = "Tasha"},
        {pronouns = "their",  name = "Fungible Asset"},
        {pronouns = "female", name = "Amira"},
        {pronouns = "female", name = "Brianna"},
        {pronouns = "female", name = "Val"},
        {pronouns = "female", name = "Ada"},
        {pronouns = "female", name = "Wren"},
        {pronouns = "female", name = "Vera"},
        {pronouns = "female", name = "Kiara"},
        {pronouns = "female", name = "Harmony"},
        {pronouns = "female", name = "Daphne"},
        {pronouns = "either", name = "MeepleCat", special_memoir = {"biter-memoirs-special.MeepleCat"}},
        {pronouns = "either", name = "nuker_man", special_memoir = {"biter-memoirs-special.nuker_man"}},
        {pronouns = "male",   name = "Mr. Whitebug", special_memoir = {"biter-memoirs-special.Mr. Whitebug"}},
        {pronouns = "either", name = "Skullbearer", special_memoir = {"biter-memoirs-special.Skullbearer"}},
    }
end

function load_defaults()
    -- All the names, pronouns, and special memoirs
    storage.biter_names = default_names()
    -- Don't calculate this so often, just store it.
    storage.biter_name_count = #storage.biter_names

    --- The number here should match the highest locale number
    storage.biter_memoir_count = 116

    ---@deprecated Now contained in name_info
    ---@type nil
    storage.biter_name_pronouns = nil
    ---@deprecated Now contained in name_info
    ---@type nil
    storage.biter_memoirs_special = nil
end